Models/CategoryProduct.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dreams.Models
{
    public class CategoryProduct
    {
        [Key]
        public int Id { get; set; } = 0;

        [Required]
        [Display(Name = "Category")]
        public int CategoryId { get; set; } = 0;

        [Required, StringLength(300)]
        public string Name { get; set; } = String.Empty;

        [StringLength(1000)]
        public string? Description { get; set; } = String.Empty;

        [StringLength(250)]
        public string? Image { get; set; } = String.Empty;

        [Required]
        [Range(0.01, 999999.99)]
        [DataType(DataType.Currency)]
        public decimal MSRP { get; set; } = 0.01M;

        [ForeignKey("CategoryId")]
        public virtual Category? Category { get; set; }// creates the association to departments
        // allows a department to be stored in an instance of a product
    }
}

Controllers/CartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Dreams.Models;
using Dreams.Services;

namespace Dreams.Controllers
{
    public class CartsController : Controller
    {
        private readonly CartService _cartService;
        private readonly ApplicationDbContext _context;

        public CartsController(CartService cartService, ApplicationDbContext context)
        {
            _cartService = cartService;
            _context = context;
            _cartService = cartService;
        }

        public async Task<IActionResult> Index()
        {
            // Get our cart (either an existing or generate a new one)
            var cart = _cartService.GetCart();

            if (cart == null)
            {
                return NotFound();
            }

            // If the cart has items, we need to add the product reference for those items
            if (cart.CartItems.Count > 0)
            {
                foreach (var cartItem in cart.CartItems)
                {
                    /*
                        SELECT * FROM Products
                        JOIN Departments ON Products.DepartmentId = Departments.Id
                        WHERE Products.Id = 1 LIMIT 1
                    */
                    var product = await _context.CategoryProducts
                        .Include(p => p.Category)
                        .FirstOrDefaultAsync(p => p.Id == cartItem.ProductId);
                    if (product != null)
                    {
                        cartItem.Product = product;
                    }
                }
            }
            return View(cart);
        }
        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            // Getting the active cart
            var cart = _cartService.GetCart();

            if (cart == null)
            {
            if (cart == null) {
                return NotFound();
            }

            // Checking if item already is in the cart
            var cartItem = cart.CartItems.Find(cartItem => cartItem.ProductId == productId);

            if (cartItem != null && cartItem.Product != null)
            {
                cartItem.Quantity += quantity; 
            }    
                cartItem.Quantity += quantity;
            }
            else
            {
                var product = await _context.CategoryProducts
                    .FirstOrDefaultAsync(p => p.Id == productId);

                if (product == null) {
                    return NotFound();
                }

                CartItem cartItem = new CartItem { ProductId = productId, Quantity = quantity, Product = product };
                cart.CartItems.Add(cartItem);
            }
            _cartService.SaveCart(cart);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int productId)
        {
            var cart = _cartService.GetCart();
            if (cart == null)
            {
                return NotFound();
            }
            var cartItem = cart.CartItems.Find(cartItem => cartItem.ProductId == productId);
            if (cartItem != null)
            {
                cart.CartItems.Remove(cartItem);
                _cartService.SaveCart(cart);
            }

            return RedirectToAction("Index");
        }
    }      
}

Controllers/CategoryProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dreams.Models;
using Microsoft.AspNetCore.Authorization;

namespace Dreams.Controllers
{
    public class CategoryProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CategoryProducts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CategoryProducts.Include(c => c.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CategoryProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CategoryProducts == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoryProducts
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // GET: CategoryProducts/Create
        [Authorize(Roles="Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: CategoryProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategoryId,Name,Description,Image,MSRP")] CategoryProduct categoryProduct)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoryProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", categoryProduct.CategoryId);
            return View(categoryProduct);
        }

        // GET: CategoryProducts/Edit/5
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CategoryProducts == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoryProducts.FindAsync(id);
            if (categoryProduct == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", categoryProduct.CategoryId);
            return View(categoryProduct);
        }

        // POST: CategoryProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryId,Name,Description,Image,MSRP")] CategoryProduct categoryProduct)
        {
            if (id != categoryProduct.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryProductExists(categoryProduct.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", categoryProduct.CategoryId);
            return View(categoryProduct);
        }

        // GET: CategoryProducts/Delete/5
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CategoryProducts == null)
            {
                return NotFound();
            }

            var categoryProduct = await _context.CategoryProducts
                .Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoryProduct == null)
            {
                return NotFound();
            }

            return View(categoryProduct);
        }

        // POST: CategoryProducts/Delete/5
        [Authorize(Roles="Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CategoryProducts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.CategoryProducts'  is null.");
            }
            var categoryProduct = await _context.CategoryProducts.FindAsync(id);
            if (categoryProduct != null)
            {
                _context.CategoryProducts.Remove(categoryProduct);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryProductExists(int id)
        {
            return (_context.CategoryProducts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/CategoryProducts/Create.cshtml
@model Dreams.Models.CategoryProduct

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CategoryProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MSRP" class="control-label"></label>
                <input asp-for="MSRP" class="form-control" />
                <span asp-validation-for="MSRP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CategoryProducts/Delete.cshtml
@model Dreams.Models.CategoryProduct

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoryProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MSRP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MSRP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CategoryProducts/Details.cshtml
@model Dreams.Models.CategoryProduct

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CategoryProduct</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MSRP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MSRP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
</div>
<div>
    <form asp-controller="Carts" asp-action="AddToCart">
        <input type="hidden" name="productId" value="@Model?.Id" />
        <input type= "number" step="1" min="1" max="99999999" name="quantity" value="1" />
        <input type="submit" value="Add to Cart" class="btn btn-success" />
    </form>
    @if(User.IsInRole("Admin")){
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
    <span>&nbsp;|&nbsp;</span>
    }
    <a asp-action="Index">Back to List</a>
</div>

Views/CategoryProducts/Edit.cshtml
@model Dreams.Models.CategoryProduct

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CategoryProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MSRP" class="control-label"></label>
                <input asp-for="MSRP" class="form-control" />
                <span asp-validation-for="MSRP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CategoryProducts/Index.cshtml
@model IEnumerable<Dreams.Models.CategoryProduct>

@{
    ViewData["Title"] = "Index";
}

<h1 class="my-3 py-3">Index</h1>

<p>
    @if (User.IsInRole("Admin")) {
        <a asp-action="Create">Create New</a>
    }
</p>

<partial name="~/Views/Shared/Products/_ProductsTablePartial.cshtml" model="Model" />

<!-- Adding the search input field here -->
@* <input type="text" id="searchInput" placeholder="Search for products...">
<button id="search"><i class="fas fa-search"></i></button> *@
@* 
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MSRP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MSRP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                @* <a asp-action="AddToCart" asp-controller="Cart" asp-route-productId="@item.Id" asp-route-quantity=1>AddToCart</a> *@
            @* </td>
        </tr>
}
    </tbody>
</table> *@